#!/bin/bash

set -o errexit -o nounset -o pipefail

replicas=({1..2}.grapheneos.org)

for replica in ${replicas[@]}; do
    echo
    echo Deploying to $replica
    echo

    rsync -rptvl --fsync --delete /etc/letsencrypt/ $replica:/etc/letsencrypt
    rsync -rptvl --fsync --delete /etc/nginx/ocsp-cache/ $replica:/etc/nginx/ocsp-cache
    ssh root@$replica nginx -s reload
done
