#!/bin/bash

set -o errexit -o nounset -o pipefail

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo deploy_static already locked >&2
    exit 1
fi

./process-static $fd

servers=({0..2}.grapheneos.org)

for server in ${servers[@]}; do
    echo $server

    remote=root@$server
    active=$(ssh $remote readlink /srv/grapheneos.org)

    if [[ $active = /srv/grapheneos.org_a ]]; then
        target=/srv/grapheneos.org_b
    else
        target=/srv/grapheneos.org_a
    fi

    echo active is $active
    echo target is $target
    echo

    ssh $remote "rm -rf $target && cp -a $active $target"
    rsync -rptcv --fsync --chmod=D755,F644 --delete static-tmp/ $remote:$target
    ssh $remote "ln -snf $target /srv/grapheneos.org && sync /srv/grapheneos.org"

    sed "s|/srv/grapheneos.org|$target|" nginx-tmp/nginx.conf > nginx-tmp/nginx.conf.root
    rsync -rptcv --fsync --chmod=D755,F644 --delete nginx-tmp/nginx.conf.root $remote:/etc/nginx/nginx.conf
    rsync -rptcv --fsync --chmod=D755,F644 --delete nginx-tmp/snippets/ $remote:/etc/nginx/snippets
    ssh $remote nginx -s reload

    echo
    echo active is now $target
    echo
done
