#!/bin/bash

set -o errexit

remote=www-data@grapheneos.org
active=$(ssh $remote readlink html)

if [[ $active = html_a ]]; then
    target=html_b
else
    target=html_a
fi

echo active is $active
echo target is $target
echo

rsync -rcve ssh --delete static/ $remote:$target
ssh $remote chmod -R a+rX $target
ssh $remote ln -snf $target html
