#!/bin/bash

set -o errexit -o nounset -o pipefail
shopt -s dotglob extglob globstar

export PATH="$PWD/node_modules/.bin:$PATH"

rm -rf static-tmp
cp -a static static-tmp
rm -rf static-tmp/js/fastboot/{!(dist),dist/!(fastboot.min.mjs|fastboot.min.mjs.map|vendor)}
mv static-tmp/js/fastboot/dist static-tmp/js/fastboot/v1.0.9

for file in static-tmp/**/*.@(json|webmanifest); do
    json_reformat -m < "$file" | sponge "$file"
done

find static-tmp -name '*.css' -exec csso {} -o {} \;
find static-tmp -name '*.js' -exec terser --ecma 2021 --module -cmo {} {} \;

replace=""
for file in static-tmp/**/*.css static-tmp/js/*.js static-tmp/mask-icon.svg; do
    hash=$(sha256sum "$file" | head -c 8)
    dest="$(dirname $file)/$hash.$(basename $file)"
    mv "$file" "$dest"
    replace+=";s|/${file#*/}|/${dest#*/}|g"
done

cp nginx/nginx.conf nginx.conf.tmp
sed -i "$replace" static-tmp/**/*.html nginx.conf.tmp

find static-tmp -name '*.html' -exec html-minifier --collapse-whitespace \
    --process-scripts "application/ld+json" --collapse-boolean-attributes \
    --remove-attribute-quotes --remove-comments --remove-empty-attributes \
    --remove-redundant-attributes --remove-script-type-attributes \
    --remove-style-link-type-attributes --sort-attributes --sort-class-name {} -o {} \;

./generate-feed.py

for file in static-tmp/**/*.@(atom|xml); do
    xmllint --noblanks "$file" --output "$file"
done

brotli_k() {
    brotli -k "$@"
}
export -f brotli_k

zopfli_preserve_time() {
    zopfli "$1"
    touch -r "$1" "$1.gz"
}
export -f zopfli_preserve_time

find static-tmp -regex '.+\.\(atom\|css\|html\|ico\|js\|json\|mjs\|pdf\|svg\|txt\|webmanifest\|xml\)' |
    parallel -q ::: brotli_k zopfli_preserve_time :::: -
