#!/bin/bash

set -o errexit -o nounset -o pipefail
shopt -s extglob globstar

export PATH="$PWD/node_modules/.bin:$PATH"

xmllint --noout static/**/*.@(html|svg|xml)
jshint --verbose static/**/*.js
stylelint static/**/*.css
validatornu --Werror --also-check-css static/**/*.@(css|html)
validatornu --Werror --skip-non-svg --no-langdetect static
