#!/bin/bash

set -o errexit -o nounset -o pipefail
shopt -s dotglob extglob globstar

export PATH="$PWD/node_modules/.bin:$PATH"

for file in static/**/*.@(json|webmanifest); do
    json_verify < "$file" >/dev/null
done

xmllint --noout static/**/*.@(html|svg|xml)
eslint static/**/*.js
stylelint static/**/*.css
validatornu --Werror --also-check-css --also-check-svg static/**/*.@(css|html|svg)
