name: Validate and process static files

on: [pull_request, push]

jobs:
  static:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        cache: npm
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.13'
        cache: pip

    - run: sudo apt-get update
    - run: sudo apt-get -y install libxml2-utils yajl-tools moreutils zopfli
    - run: npm ci --ignore-scripts
    - run: 'pip install --require-hashes --only-binary :all: -r requirements.txt'

    - name: process static
      run: ./process-static
